name: Demo CI/CD

# Workflow dijalankan saat ada push ke branch main
on:
  push:
    branches: ["main"]

jobs:
  demo-deploy:
    # Menggunakan runner lokal (self-hosted)
    runs-on: self-hosted

    steps:
      # 1. Ambil perubahan kode terbaru
      - name: 1. Ambil perubahan kode
        uses: actions/checkout@v3

      # 2. Simulasi install dependency
      - name: 2. Simulasi Install Dependency
        run: echo "Sedang menginstall library yang dibutuhkan..."

      # 3. Membuat file surat
      - name: 3. Membuat surat
        shell: cmd
        run: |
          echo Halo! Aku Liz dari Lumiere. > surat_dari_liz.txt
          echo Aku bikin surat ini otomatis lho, Dibikinnya pas tanggal %DATE% jam %TIME% >> surat_dari_liz.txt

      # 4. Selesai
      - name: 4. Selesai
        run: echo "Deployment Berhasil!"
